Repository RuanAragao/calculator, pull requests merged in 2023-10, with the labels that each got.

#7 Favicon issue is resolved
  .DS_Store
  README.md
  img/.DS_Store
  img/favicons/.DS_Store
  img/favicons/favicon-192.png
  img/favicons/favicon-512.png
  img/favicons/favicon-64.png
  index.html
  manifest.webmanifest
Labels: hacktoberfest-accepted, hacktoberfest

#9 Closes#6
  calculators/example-calculator/index.html
  calculators/example-calculator/main.js
  calculators/example-calculator/script.js
  calculators/example-calculator/style.css
  calculators/example-calculator/utils.css
Labels: hacktoberfest

#23 Add converter temperatura calculator
  calculators/temperature-calculator/index.html
  calculators/temperature-calculator/script.js
  calculators/temperature-calculator/style.css
  calculators/temperature-calculator/utils.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#36 Add tip calculator
  calculators/tip-calculator/index.html
  calculators/tip-calculator/script.js
  calculators/tip-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#37 add px to em project
  calculators/PX-to-EM-converter/index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#38 contribution guidelines added to README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#39 Update README.md
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#40 feat: add count by weight calculator
  calculators/.keep
  calculators/count-by-weight/index.html
  calculators/count-by-weight/main.js
  calculators/count-by-weight/style.css
  index.html
Labels: hacktoberfest

#58 Temperature Calculator Ready
  calculators/temperature-calculator/index.html
  calculators/temperature-calculator/script.js
  calculators/temperature-calculator/style.css
Labels: hacktoberfest

#65 Add a minimal PR template and .gitignore file
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .gitignore
Labels: hacktoberfest-accepted, hacktoberfest

#66 feat: add checklist item
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: hacktoberfest-accepted, hacktoberfest

#68 change pr template
  .github/pull_request_template.md
Labels: hacktoberfest-accepted, hacktoberfest

#71 closes #63 (Adding Number System Calculator)
  calculators/number-system-calculator/index.html
  calculators/number-system-calculator/script.js
  calculators/number-system-calculator/styles.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#83 Add information in the README.md
  README.md
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#85 Closes #84 (Color Converter)
  calculators/color-converter/index.html
  calculators/color-converter/script.js
  calculators/color-converter/style.css
  index.html
Labels: hacktoberfest

#87 added CGPA Calculator
  README.md
  calculators/cgpa-calculator/README.md
  calculators/cgpa-calculator/calculator.js
  calculators/cgpa-calculator/index.html
  calculators/cgpa-calculator/styles/app.css
  calculators/cgpa-calculator/styles/darkmode.css
  index.html
Labels: hacktoberfest

#91 Added Quadratic Root Calculator
  calculators/root-calculator/index.html
  calculators/root-calculator/script.js
  calculators/root-calculator/styles.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#82 closes #79(Added Bitwise calculator)
  calculators/bitwise-calculator/index.html
  calculators/bitwise-calculator/script.js
  calculators/bitwise-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#69 Added Investment calculator correctly #43
  calculators/invesrment-calculator/index.html
  calculators/invesrment-calculator/script.js
  calculators/invesrment-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#60 Discount calculator
  calculators/discount-calculator/discount-calculator.css
  calculators/discount-calculator/discount-calculator.js
  calculators/discount-calculator/index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#77 Closes #75
  calculators/compound-interest-calculator/index.html
  calculators/compound-interest-calculator/script.js
  calculators/compound-interest-calculator/styles.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#89 Body-fat calculator closes #88
  calculators/Body Fat-calculator/index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#93 add distance converter
  calculators/distance-calculator/index.html
  calculators/distance-calculator/script.js
  calculators/distance-calculator/style.css
  calculators/distance-calculator/utils.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#97 Closes #78
  calculators/2-8-16-calculator/icon.ico
  calculators/2-8-16-calculator/index.html
  calculators/2-8-16-calculator/script.js
  calculators/2-8-16-calculator/stylesheet.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#107 Closes #94
  calculators/binary-operations-calculator/index.html
  calculators/binary-operations-calculator/script.js
  calculators/binary-operations-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#24 General Purpose Calculator
  calculators/general-purpose-calculator/cal.css
  calculators/general-purpose-calculator/cal.js
  calculators/general-purpose-calculator/index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#109 Added Unit Convertor #44
  calculators/unit-convertor/index.html
  calculators/unit-convertor/script.js
  calculators/unit-convertor/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#110 Added coordinate distance calculator
  calculators/Distance-between-two-coordinates-calculator/index.html
  calculators/Distance-between-two-coordinates-calculator/script.js
  calculators/Distance-between-two-coordinates-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#111 added Roman-number-calculator
  calculators/Roman-number-calculator/index.html
  calculators/Roman-number-calculator/script.js
  calculators/Roman-number-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#115 added complex number calculator #103
  calculators/complex-number-calculator/index.html
  calculators/complex-number-calculator/script.js
  calculators/complex-number-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#117 School Calculator
  calculators/school-calculator/index.html
  calculators/school-calculator/script.js
  calculators/school-calculator/style.css
  index.html
Labels: hacktoberfest-accepted, hacktoberfest
